name: application

releases:
- name: application
  version: latest
- name: "bpm"
  version: "1.1.15"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.15"
  sha1: "0d48aa01a65b947b97570234eb2401e821a8bd35"

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 1

instance_groups:
- name: application-vm
  instances: 1
  vm_type: minimal
  vm_extensions:
  - application_load_balancer
  stemcell: xenial
  azs:
  - z1
  networks:
  - name: default
  jobs:
  - name: bpm
    release: bpm
  - name: application
    release: application
    properties:
      port: 9090

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest
