---
name: minio

releases:
- name: minio
  version: latest

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: minio
  azs: [z1]
  instances: 1
  jobs:
  - name: minio-server
    release: minio
    templates:
    - name: minio-server
    properties:
      credential:
        accesskey: minio
        secretkey: minio123
      port: 9000
  networks:
  - name: default
  vm_type: default
  vm_extensions:
    - minio_load_balancer
  persistent_disk_type: 5GB
  stemcell: xenial

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 10
